"""empty message

Revision ID: 33bc13a1de96
Revises: b43397c24097
Create Date: 2023-05-29 21:54:40.885696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33bc13a1de96'
down_revision = 'b43397c24097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('people_name', sa.INTEGER, nullable=True))
        batch_op.create_foreign_key(None, 'people', ['people_name'], ['id'])

    # ### end Alembic commands ###
