"""empty message

Revision ID: 56d1680296e3
Revises: de3d2ab62fed
Create Date: 2023-05-29 21:36:45.188089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d1680296e3'
down_revision = 'de3d2ab62fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:

        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:

        batch_op.add_column(sa.Column('user_id', sa.INTEGER(),
                            autoincrement=False, nullable=True))

    # ### end Alembic commands ###
