"""empty message

Revision ID: 817c6da183d3
Revises: 0bd0f2f469e2
Create Date: 2023-05-29 20:15:35.000280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817c6da183d3'
down_revision = '0bd0f2f469e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
